// <auto-generated />
using System;
using EVO_DAL.Models.Exception;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EVO_DAL.Migrations.EVODBContextSingletonMigrations
{
    [DbContext(typeof(EVODBContextSingleton))]
    partial class EVODBContextSingletonModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EVO_Models.Entities.ExceptionTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExceptionMethod")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ExceptionSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExceptionStackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("exceptiontracking");
                });
#pragma warning restore 612, 618
        }
    }
}
